#+latex_header: \pagestyle{empty}
#+OPTIONS: num:notoc

\pagenumbering{gobble}
* Henrik Zenkert

- henrik.zenkert@gmail.com
- +45 31414643
- Islands Brygge 60, 2300, Copenhagen

** Education/Uddannelse

*Diplomingeniør Softwareteknologi | /2021-/*

Danmarks Tekniske Universitet | Kongens Lyngby, Danmark

*Objektorienterad programmering och design | /2019/*

Luleå tekniska universitet | Luleå, Sverige

** Projects/Projekter

*** Operadocs

[[https://operadocs.com/][Link]] |
[[https://github.com/YesSeri/opera-docs][GitHub]]

This is a webpage where you can find sheet music for free for operas.
Having worked as an opera singer for many years, I know how hard it can
be to find the correct sheet music, quickly. All the scores I upload are
no longer under copyright protection.

- Next.js
- MySQL
- Python

*** Bubblewrap

[[https://yesseri.github.io/bubblewrap.html][Link]] |
[[https://github.com/YesSeri/bubble-wrap][GitHub]]

A game written in Rust and Wasm. Survive the bubbles that attack you.
Everything is written from scratch, no game engine or things like that.
Wasm4 contains a set of basic functions such as painting rectangles and
setting individual pixels to one of four chosen colors. Play with arrow
keys and Z and X.

- Rust
- I made a wrapper game engine around wasm4

*** Pianisto

[[https://pianisto.net/][Link]] |
[[https://github.com/YesSeri/svelte-piano][GitHub]]

A piano that you can play online. It is written in Svelte and uses the
Tone.js library. It was inspired by the piano app Real Piano. I wanted
to create an ad-free alternative.

- HTML
- CSS
- Javascript

** Work Experience/Erhvervserfaring

*** IT consultant - Zenjon AB 2018-2022

- Going through code submissions and look for plagiarized material.
- Setting up scripts for more efficiently processing spam. Primarily
  done in JavaScript and GreaseMonkey to make the internal systems more
  efficient.
- Admin duties, checking for plagiarism, monitoring spam comments.
